# Generated by Django 5.2.13 on 2026-04-17 14:24

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='company',
            name='location_radius_meters',
            field=models.PositiveIntegerField(default=200, help_text='Office se kitne meter tak attendance allow hai'),
        ),
        migrations.AddField(
            model_name='company',
            name='office_latitude',
            field=models.DecimalField(decimal_places=7, default=Decimal('24.8609660'), help_text='Office ka GPS latitude — purani rows migrate ke liye default; admin se sahi set karein.', max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='office_longitude',
            field=models.DecimalField(decimal_places=7, default=Decimal('67.0011000'), help_text='Office ka GPS longitude — default migrate; admin se sahi set karein.', max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='Asia/Karachi', help_text='IANA timezone, e.g. Asia/Karachi, UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='work_end_time',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Attendance window end (local time)'),
        ),
        migrations.AddField(
            model_name='company',
            name='work_start_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Attendance window start (local time)'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(help_text='Company timezone ke hisaab se din'),
        ),
    ]
