/** Attendance dashboard UI strings (English). */

export const L = {
  statusComplete: "Complete",
  statusCompleteDetail: "Checked in & out",
  statusPending: "Pending",
  statusPendingDetail: "Check-in only (no check-out yet)",
  statusAbsent: "Absent",
  statusAbsentDetail: "No check-in recorded",
  statusFake: "Fake",
  statusFakeDetail: "Outside company attendance radius",

  checkIn: "Check-in",
  checkOut: "Check-out",
  checkOutNotYet: "Check-out not marked yet",

  thDay: "Day",
  thCheckInTime: "Check-in time",
  thCheckOutTime: "Check-out time",
  thLocation: "Location",
  coordNotRecorded: "GPS not saved for this mark",
  mapLink: "Map",
  thStatus: "Status",
  thPhotos: "Photos",
  recordsTitle: "Attendance history",
  noRecords: "No records yet.",

  linkCheckInPhoto: "Check-in photo",
  linkCheckOutPhoto: "Check-out photo",
  dayDetailOpenFull: "Open full size",

  pieComplete: "Complete",
  piePending: "Pending",
  pieAbsent: "Absent",
  pieFake: "Fake",

  todayPrefix: "Today",
  companyCalPhrase: "Company calendar date",
  noRecordToday: "No attendance marked for today yet.",

  cameraSectionTitle: "Live camera",
  cameraSectionHelp: "Gallery uploads are not allowed — capture from the device camera only.",
  cameraStart: "Start camera",
  cameraCapture: "Capture photo",
  cameraStop: "Stop camera",

  submitSectionTitle: "Submit for today",
  submitSectionHelp:
    "One tap on Check in or Check out asks for your location and camera, captures a live photo, and sends attendance automatically.",
  monthByDateTitle: "Attendance by day",
  monthByDateHelp: "Tap a row to open photo links for that day.",
  monthPickerLabel: "Month",
  dayDetailChartTitle: "That day",
  dayDetailClose: "Close",
  dayDetailNoPhotos: "No photos for this day.",
  permModalLocationTitle: "Turn on location",
  permModalLocationBody:
    "Allow location for this site (address bar lock or info icon → Site settings → Location → Allow). Turn on GPS / location services on your device, then try Check in or Check out again.",
  permModalCameraTitle: "Turn on camera",
  permModalCameraBody:
    "A live photo is required. Allow camera access when the browser asks, or enable it in site settings for this page, then try again.",
  permModalClose: "Got it",
  liveCaptureTitleCheckIn: "Check in — camera",
  liveCaptureTitleCheckOut: "Check out — camera",
  liveCaptureLocating: "Getting location…",
  liveCaptureStartingCamera: "Starting camera…",
  liveCaptureHelp: "You should see yourself below. When ready, tap Capture & submit.",
  btnCancelLiveCapture: "Cancel",
  btnCaptureSubmit: "Capture & submit",
  liveCaptureSaving: "Saving…",
  liveCaptureGotLocation: "Location received — it will be sent with your photo.",
  permModalDetailLabel: "Details",
  btnSubmitCheckIn: "Check in",
  btnSubmitCheckOut: "Check out",
  submitCardArrivalTag: "Arrival",
  submitCardLeavingTag: "Leaving",
  submitCardArrivalHelp: "Records your first mark of the day.",
  submitCardLeavingHelp: "Available after check-in, before the day is closed.",
  submitNextCheckIn: "Next: tap Check in when you arrive at work.",
  submitNextCheckOut: "Next: tap Check out when you leave.",
  submittingCheckIn: "Checking in…",
  submittingCheckOut: "Checking out…",
  hintSubmitComplete: "Today's check-in and check-out are already saved.",
  hintSubmitCheckInBlocked: "You already checked in — use Check out when you leave.",
  hintSubmitCheckOutNeedsIn: "Check in first; there is no record for today yet.",
  hintSubmitCheckOutDone: "You already checked out today.",

  field1Tag: "Section 1 — Summary",
  field1Title: "Last 14 days: complete, pending, fake, absent",
  field1Help:
    "Complete = check-in and check-out. Pending = check-in only. Fake = outside company radius. Absent = no mark that day.",

  field2Tag: "Section 2 — Daily breakdown",
  field2Title: "One column per day",
  field2Help: "Green = complete, amber = pending, red = fake, grey = absent. Your record only.",

  coTeamHeader: "Team reports",
  coTeamTitle: "Your company only",
  coTeamHelp: "Team totals, the member table, and the selected member’s daily chart are grouped in one panel.",
  coOpenMemberPage: "View full record →",

  coF1: "Section 1 — Team summary",
  coF1Title: "All members combined",
  coF1Desc: "Sum of all member-days in this chart only.",

  coF2: "Section 2 — Member selection",
  coF2Title: "Which member's data to view",
  coF2Desc: "Pick a member — details follow in the next sections.",
  coMemberLabel: "Member",

  coF3: "Section 3 — Member counts",
  coF3Title: "Count summary",

  coF4: "Section 4 — Daily columns",
  coF4Title: "One bar per day",
  coF4Desc: "Breakdown for the member chosen in Section 2 only.",

  coDuration: "Duration (days)",
  coRefresh: "Refresh",
  coNoMembers: "No members yet — add a member first.",

  coMembersRosterTitle: "Your team",
  coMembersRosterHelp: "People you have added to this company. Tap one to see their counts and day-by-day table.",
  coPickMemberTitle: "Member overview",
  coPickMemberHelp: "Summary for the date range above. Absent = no attendance mark that day (not the same as approved paid leave).",
  coStatFullDays: "Full days",
  coStatFullDaysSub: "In & out both",
  coStatPending: "Pending",
  coStatPendingSub: "Check-in only",
  coStatFake: "Fake",
  coStatFakeSub: "Outside radius",
  coStatAbsent: "No mark",
  coStatAbsentSub: "No attendance",
  coStatPresent: "Days with check-in",
  coStatPresentSub: "Complete + pending",
  coDailyTableTitle: "Day-by-day",
  coThDate: "Date",
  coThDay: "Day",
  coThStatus: "Status",
  coTeamMixTitle: "All members combined",

  coBackToTeam: "← Back to team",
  coMemberReportTitle: "Attendance record",
  coMemberReportSubtitle: "Day-by-day for the range below. Members mark their own attendance.",
  coMemberPieTitle: "This member — complete, pending, fake, absent",
} as const;

export const chartTooltip: Record<"complete" | "pending" | "absent" | "fake", string> = {
  complete: "Complete (checked in & out)",
  pending: "Pending (check-in only)",
  absent: "Absent (no mark)",
  fake: "Fake (outside company radius)",
};
